#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
  build_issue1_repro_bundle.sh \
    --board-root DIR \
    --oracle-root DIR \
    --repo-root DIR \
    --decision-table FILE \
    --output TAR_GZ

Builds the sanitized Stage63 issue #1 attachment. The bundle contains only
tiny synthetic repro graphs, fixed inputs, independent expected outputs, the
neutral ORT C++ runner, and the independent plugin smoke source.
EOF
}

board_root=
oracle_root=
repo_root=
decision_table=
output=

while (($#)); do
    case "$1" in
        --board-root) board_root=${2:?}; shift 2 ;;
        --oracle-root) oracle_root=${2:?}; shift 2 ;;
        --repo-root) repo_root=${2:?}; shift 2 ;;
        --decision-table) decision_table=${2:?}; shift 2 ;;
        --output) output=${2:?}; shift 2 ;;
        --help|-h) usage; exit 0 ;;
        *) printf 'unknown argument: %s\n' "$1" >&2; usage >&2; exit 2 ;;
    esac
done

for value in board_root oracle_root repo_root decision_table output; do
    test -n "${!value}" || {
        printf 'missing --%s\n' "${value//_/-}" >&2
        exit 2
    }
done

board_root=$(realpath "$board_root")
oracle_root=$(realpath "$oracle_root")
repo_root=$(realpath "$repo_root")
decision_table=$(realpath "$decision_table")
output=$(realpath -m "$output")

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
root="$tmp/ISSUE_1_RT206_MINIMAL_REPRO_BUNDLE"
mkdir -p "$root/models" "$root/inputs" "$root/expected" \
    "$root/runner" "$root/plugin" "$root/results"

install -m 0644 "$board_root/repros/03_conv_qdq.onnx" "$root/models/A0_qdq_conv.onnx"
install -m 0644 "$board_root/repros/15_conv_qdq_attr_kernel_shape.onnx" \
    "$root/models/A1_qdq_conv_kernel_shape.onnx"
install -m 0644 "$board_root/repros/08_qlinearconv.onnx" "$root/models/B_qlinearconv.onnx"
install -m 0644 "$board_root/repros/10_qlinearmatmul_smoke.onnx" \
    "$root/models/C_qlinearmatmul.onnx"
install -m 0644 "$board_root/repros/input_1x3x8x8_f32.bin" \
    "$root/inputs/input_1x3x8x8_f32.bin"
install -m 0644 "$board_root/repros/input_1x4_f32.bin" \
    "$root/inputs/input_1x4_f32.bin"

for case_id in A0 A1 B C; do
    install -m 0644 "$oracle_root/${case_id}_independent_oracle.bin" \
        "$root/expected/${case_id}_independent_oracle.bin"
done

install -m 0644 "$repo_root/custom_int8_engine/tools/bench_stage46_ort_runtime.cpp" \
    "$root/runner/ort_runtime_runner.cpp"
install -m 0644 "$repo_root/vendor_ort_validation/verify_tiny_oracles.py" \
    "$root/runner/verify_tiny_oracles.py"
install -m 0644 "$repo_root/custom_int8_engine/tools/stage46_plugin/stage46_u8_xor_plugin.cpp" \
    "$root/plugin/stage46_u8_xor_plugin.cpp"
install -m 0644 "$repo_root/custom_int8_engine/tools/stage46_plugin/CMakeLists.txt" \
    "$root/plugin/CMakeLists.txt"
install -m 0644 "$repo_root/LICENSE" "$root/LICENSE"
install -m 0644 "$board_root/plugin/stage46_u8_xor.onnx" \
    "$root/plugin/stage46_u8_xor.onnx"
install -m 0644 "$board_root/plugin/stage46_u8_xor_input.bin" \
    "$root/plugin/stage46_u8_xor_input.bin"
install -m 0644 "$board_root/plugin/stage46_u8_xor_expected.bin" \
    "$root/plugin/stage46_u8_xor_expected.bin"
install -m 0644 "$decision_table" "$root/results/issue1_final_decision_table.tsv"

cat >"$root/README.md" <<'EOF'
# SpacemiT ORT 2.0.6 issue #1 minimal repros

This public-safe attachment contains only generated tiny ONNX graphs and
inputs. It contains no YOLO model, trained weights, COCO data, camera media,
vendor binaries, custom-executor implementation, credentials, or private
machine paths.

The included runner and independent plugin smoke source are distributed under
the repository's AGPL-3.0-or-later terms; see `LICENSE`.

## Cases

- `A0`: Q/DQ Conv without `kernel_shape`.
- `A1`: Q/DQ Conv with explicit `kernel_shape=[3,3]`.
- `B`: minimal `QLinearConv`.
- `C`: minimal `QLinearMatMul`.
- `plugin/`: independent uint8 custom-operator execution smoke.

The `expected/` files are generated by the independent local operator oracle,
not by SpacemiT EP output.

## Build

Set `CXX` to a RISC-V compiler and `ORT_ROOT` to one extracted official
SpacemiT ORT package:

```bash
"${CXX}" -std=c++17 -O2 \
  -I"${ORT_ROOT}/include" \
  runner/ort_runtime_runner.cpp \
  -L"${ORT_ROOT}/lib" -lonnxruntime -ldl -pthread \
  -o ort_runtime_runner
```

Run with an explicit version-local loader path. For example:

```bash
LD_LIBRARY_PATH="${ORT_ROOT}/lib" taskset -c 0 timeout 30s \
  ./ort_runtime_runner \
  --provider spacemit \
  --model models/B_qlinearconv.onnx \
  --input inputs/input_1x3x8x8_f32.bin \
  --output B.out \
  --opt-level disable \
  --intra-threads 1 --inter-threads 1

cmp B.out expected/B_independent_oracle.bin
```

Repeat with CPU EP as the semantic/runtime control. Capture stdout, stderr,
exit status, terminating signal, loaded library hashes, and CPU affinity.

The plugin smoke is built with:

```bash
cmake -S plugin -B plugin-build \
  -DSPACEMIT_ORT_ROOT="${ORT_ROOT}" \
  -DCMAKE_BUILD_TYPE=Release
cmake --build plugin-build
```

The Stage63 report and decision table distinguish link/load success from
actual plugin assignment and exact execution.
EOF

(
    cd "$root"
    find . -type f ! -name SHA256SUMS -print0 |
        sort -z |
        xargs -0 sha256sum >SHA256SUMS
)

mkdir -p "$(dirname "$output")"
epoch=${SOURCE_DATE_EPOCH:-0}
tar --sort=name --mtime="@${epoch}" --owner=0 --group=0 --numeric-owner \
    -C "$tmp" -cf - ISSUE_1_RT206_MINIMAL_REPRO_BUNDLE |
    gzip -n >"$output"
checksum_path="${output%.tar.gz}.sha256"
(
    cd "$(dirname "$output")"
    sha256sum "$(basename "$output")" >"$(basename "$checksum_path")"
)
